default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <% services = JSON.parse ENV['VCAP_SERVICES']
     postgres = services["elephantsql"].first["credentials"] %>
  url: <%= postgres["uri"] %>
  pool: 5
  timeout: 5000
